name: churn-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - numpy=1.24.3
  - pandas=2.1.3
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - plotly=5.17.0
  - pip:
    - tensorflow==2.15.0
    - joblib==1.3.2
    - streamlit==1.28.0
    - fastapi==0.104.0
    - uvicorn==0.24.0
    - pytest==7.4.3
    - black==23.11.0
    - isort==5.12.0
    - flake8==6.1.0
